addpath(genpath(pwd));
modules = {'simulation_params', 'apply_scenario_params', 'run_unified_once', ...
    'aircraft_trajectory_create', ...
    'aircraft_trajectory_interpolate', 'aircraft_trajectory_locate', ...
    'build_truth_scenario', 'estimate_adsb_bias', 'generate_all_radar_detections', ...
    'bistatic_inverse_solver', 'radar_coverage_check', ...
    'generate_frame_detections_multi', ...
    'ukf_jichu', 'ukf_zishiying', 'ukf_imm', 'ukf_dispatch', 'adapt_q', ...
    'track_initiation', 'track_management', ...
    'multi_track_runner_kf', 'multi_track_start', 'post_init_multi', ...
    'jpda_multi', 'nn_associate', 'pda_weight', ...
    'time_align_tracks', 'track_matcher', 'run_track_fusion', ...
    'track_fusion_algorithms', 'regularize_cov', ...
    'evaluate_all', ...
    'plot_results', 'plot_results_multi', 'plot_scene_overview', ...
    'plot_point_cloud_3d', 'plot_turn_spatial', ...
    'skywave_geometry', 'sphere_utils_azimuth', ...
    'sphere_utils_haversine_distance', 'sphere_utils_destination_point', ...
    'sphere_utils_radial_velocity', 'sphere_utils_interpolate_great_circle', ...
    'coord_systems_lla_to_ecef', 'sphere_utils_seconds_to_datetime_str'};
n_ok = 0; n_fail = 0;
for i = 1:length(modules)
    fn = modules{i};
    try
        which(fn);
        n_ok = n_ok + 1;
    catch
        fprintf('FAIL: %s\n', fn);
        n_fail = n_fail + 1;
    end
end
fprintf('\nSummary: %d OK, %d FAIL out of %d\n', n_ok, n_fail, length(modules));
